### PR TITLE
Slider fix

### PR DESCRIPTION
**Pull request by asadzeynal**
Hey @prophittcorey

This is a small fix for the slider being unresponsive to being moved. Should be working fine now, however I did not have enough time to test it properly

### CODE REVIEW

**Comment by prophittcorey** [comment]
@asadzeynal can you provide some information on how to reproduce the unresponsiveness (browser, os, steps, etc)? It seems to be responsive in the browsers I have tested. I tried the PR out and the behavior seems identical to the initial behavior.

**Comment by asadzeynal** [comment]
@prophittcorey I tested it on two machines, linux and windows, both on latest chrome and firefox. 
If I spam on different locations of the range input, it does not move the song to that point half of the time. Additionally when I grab the slider point and drag it and stop at any point without unclicking the mouse, the the point runs away to wherever it should be on the timeline according to the time.
If that's intended, my apologies, that's my first ever contribution to an open repo. If you want me to show the behavior to you, feel free to contact me.

**Comment by prophittcorey** [comment]
@asadzeynal I took a look and I believe I know what you are referring to. I tried to fix it using "on input" instead of "on change" slider events. I also added keyboard shortcuts for the arrows/vim keys, etc. Could you try the current version and see if the slider behaves better this way? Thanks for the PR and bringing it to my attention!

**Comment by asadzeynal** [comment]
@prophittcorey Works perfectly now, nice fix!

**Comment by prophittcorey** [comment]
@asadzeynal thanks for the confirmation!

**Pull request closed without merging**
